MF:
  lr: 0.001
  net:
    W_0_hidden: 512
    f_act: leakyrelu
    f_num_hid_layers: 4
    f_num_hidden: 64
    g_act: leakyrelu
    g_num_hid_layers: 4
    g_num_hidden: 64
    label_f: false
    label_g: false
    label_x: 0
    label_y: 0
    num_cond_inputs: 1
    num_inputs: 1
    sigma: 3
NF: null
dataset:
  dataset_type: co2c0000348/co2c0000348.rd.016
  path: /global/path/data/EEG/
  scale_t: 1
  seed: 5
  simulation: false
  split_size: 0.8-0.1-0.1-0.8
  split_type: both
  subset_time: null
head: EEG
loader:
  batch_size_paths: 5
  batch_size_points: 1024
n_runs: 5
n_tries: 1
optimizer:
  n_epochs: 500
  name: AdamW
other:
  loss_type: gaussian
  test_n_particles: 100
  test_y_samp_size: 128
  train_y_samp_size: 128
