MF: null
MLP:
  lr: 0.0001
  net:
    act: leakyrelu
    grad_sigma: false
    num_cond_inputs: 1
    num_hid_layers: 8
    num_hidden: 128
    num_inputs: 2
    num_outputs: 2
    sigma: 1
NF: null
dataset:
  T: 0.1
  datatype: s
  generative: true
  n_bridge: 1
  n_points: 50
  n_samples: 2000
  simulation: true
head: s
loader:
  batch_size_paths: 200
  batch_size_points: 512
n_runs: 5
n_tries: 1
optimizer:
  n_epochs: 2000
  name: AdamW
other:
  loss_type: girsanov
  test_n_particles: 500
  test_y_samp_size: 128
  train_y_samp_size: 128
